services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - ckan
    ports:
      - "3000:3000"
    environment:
      - API_KEY=
      - CKAN_BASE_URL=http://ckan:4000
      - EMBEDDING_SERVICE_URL=http://embedding_service:8000/embed
      - TF_SERVING_URL=http://tensorflow:8501/v1/models/activity_predictor:predict
    volumes:
      - ./frontend/app/predict/api/model_metadata.json:/app/predict/api/model_metadata.json
    networks:
      - ckan-network
    profiles:
      - ignore # This excludes it from a standard 'up' when you want to run yarn dev with the backend. Disable this line to run the container.
  ckan:
    platform: linux/amd64
    build:
      context: ckan
      dockerfile: Dockerfile
    depends_on:
      - db
      - solr
      #- redis
    ports:
      - "4000:4000"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:${POSTGRES_PASSWORD:-password}@db/ckan_default
      - CKAN_SOLR_URL=${CKAN_SOLR_URL:-http://solr:8983/solr/ckan}
      - CKAN_REDIS_URL=${CKAN_REDIS_URL:-redis://redis:6379/1}
      - CKAN_DATADIC_URL=postgresql://datastore_default:${POSTGRES_PASSWORD}@db/datastore_default
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan_default:${POSTGRES_PASSWORD:-password}@db/datastore_default
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_default:${POSTGRES_PASSWORD:-password}@db/datastore_default
      - CKAN_SITE_URL=${CKAN_SITE_URL:-http://localhost:4000}
      - CKAN_BEAKER_SESSION_SECRET=${CKAN_BEAKER_SESSION_SECRET:-secret}
      - CKAN_INI=${CKAN_INI:-/srv/app/ckan.ini}
      - CKAN_SYSADMIN_NAME=${CKAN_SYSADMIN_NAME:-admin}
      - CKAN_SYSADMIN_PASSWORD=${CKAN_SYSADMIN_PASSWORD:-password}
      - CKAN_SYSADMIN_EMAIL=${CKAN_SYSADMIN_EMAIL:-admin@example.com}
      - POSTGRES_USER=${POSTGRES_USER:-ckan_default}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - UWSGI_OPTS=--plugins python3 --http-socket [::]:4000 --wsgi-file /srv/app/wsgi.py --module wsgi:application --master --enable-threads --lazy-apps -p 2 -L -b 32768 --vacuum --harakiri 60
      - CKAN_BASE_URL=http://ckan:4000/
    volumes:
      - ckan-data:/var/lib/ckan
      - ./ckan/ckan.ini:/srv/app/ckan.ini:ro
      - ./ckan/ckan-config.yaml:/srv/app/ckan-config.yaml:ro
      - ./ckan/schema.yaml:/srv/app/schema.yaml:ro
      - ./ckan/ckan-init.py:/srv/app/ckan-init.py:ro
    #tmpfs:
    #  - /var/lib/ckan:uid=92,gid=92,mode=0777
    networks:
      - ckan-network
  tensorflow:
    build:
      context: tensorflow
      dockerfile: Dockerfile
    ports:
     - "8501:8501"
    networks:
      - ckan-network
    volumes:
      - ./tensorflow/tf_serving_models:/models/
  embedding_service:
    build:
      context: tensorflow
      dockerfile: Dockerfile.embedding
    ports:
      - "8000:8000"
    networks:
      - ckan-network
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-ckan_default}
      - POSTGRES_DB=${POSTGRES_DB:-ckan_default}
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - ckan-network
  solr:
    platform: linux/amd64
    image: ckan/ckan-solr:2.10-solr9
    networks:
      - ckan-network
  redis:
    image: redis:6-alpine
    networks:
      - ckan-network
networks:
  ckan-network:
    driver: bridge
volumes:
  ckan-data:
  db-data:
