[app:main]
use = egg:ckan
full_stack = true
static_run_control = false
cache_dir = /tmp/%(ckan.site_id)s
beaker.session.key = ckan

# These will be overridden by environment variables if set
sqlalchemy.url = postgresql://ckan_default:password@db/ckan_default
ckan.datastore.write_url = postgresql://datastore_default:password@db/datastore_default
ckan.datastore.read_url = postgresql://datastore_default:password@db/datastore_default
solr_url = http://solr:8983/solr/ckan
ckan.redis.url = redis://redis:6379/1
ckan.site_url = http://localhost:4000
beaker.session.secret = secret

ckan.site_id = default
ckan.plugins = stats text_view geo_view datastore spatial_metadata spatial_query harvest ckan_harvester dcat dcat_rdf_harvester dcat_json_harvester waf_harvester doc_harvester scheming_datasets scheming_groups scheming_organizations resource_proxy check_link
# image_view recline_view recline_view
ckan.views.default_views = text_view  geo_view

ckan.storage_path = /var/lib/ckan
ckan.max_resource_size = 100
ckan.max_image_size = 2
# needed for redis connection in docker
ckan.harvest.mq.hostname = redis

ckanext.dcat.rdf.profiles = euro_dcat_ap

# Logging
[loggers]
keys = root, ckan, ckanext

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console

[logger_ckan]
level = INFO
handlers = console
qualname = ckan

[logger_ckanext]
level = INFO
handlers = console
qualname = ckanext

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
