#!/bin/bash
set -e

DATASTORE_USER="${POSTGRES_USER:-ckan_default}"
DATASTORE_PASSWORD="${POSTGRES_PASSWORD:-password}"

DATASTORE_DB="ckan_default"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    /*DROP USER IF EXISTS "$DATASTORE_USER";*/
    /*CREATE USER "$DATASTORE_USER" WITH PASSWORD 'password';*/
    DROP DATABASE IF EXISTS "$DATASTORE_DB";
    CREATE DATABASE "$DATASTORE_DB" OWNER "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$DATASTORE_DB" TO "$POSTGRES_USER";
    GRANT CONNECT ON DATABASE "$DATASTORE_DB" TO "$DATASTORE_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DATASTORE_DB" <<-EOSQL
    GRANT USAGE ON SCHEMA public TO "$DATASTORE_USER";
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO "$DATASTORE_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "$DATASTORE_USER";
EOSQL

DATASTORE_DB="datastore_default"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    /*DROP USER IF EXISTS "$DATASTORE_USER";*/
    /*CREATE USER "$DATASTORE_USER" WITH PASSWORD 'password';*/
    DROP DATABASE IF EXISTS "$DATASTORE_DB";
    CREATE DATABASE "$DATASTORE_DB" OWNER "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$DATASTORE_DB" TO "$POSTGRES_USER";
    GRANT CONNECT ON DATABASE "$DATASTORE_DB" TO "$DATASTORE_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DATASTORE_DB" <<-EOSQL
    GRANT USAGE ON SCHEMA public TO "$DATASTORE_USER";
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO "$DATASTORE_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "$DATASTORE_USER";
EOSQL
